version: 2

models:
  - name: customers
    description: One record per customer
    columns:
      - name: customer_id
        description: Primary key
        tests:
          - unique
          - not_null
      - name: first_order_date
        description: NULL when a customer has not yet placed an order.
      - name: lifetime_value
        description: Total dollar value of all customer's orders (including returned orders)

  - name: stg_customers
    description: This model cleans up customer data
    columns:
      - name: customer_id
        description: Primary key
        tests:
          - unique
          - not_null

  - name: stg_orders
    description: This model cleans up order data
    columns:
      - name: order_id
        description: Primary key
        tests:
          - unique
          - not_null
      - name: order_status
        description: '{{ doc("order_status") }}'
        tests:
          - accepted_values:
              values: ['placed', 'shipped', 'completed', 'return_pending', 'returned']

  - name: stg_payments
    description: Cleans up payments data
    columns:
      - name: payment_id
        description: Primary key
        tests:
          - unique
          - not_null
      - name: order_id
        tests:
          - not_null

  - name: orders
    descriptions: Brings together orders with their payment information
    columns:
      - name: customer_id
        tests:
          - not_null
      - name: order_date
        tests:
          - not_null
      - name: order_id
        description: Primary key
        tests:
          - unique
          - not_null